name: CI

on:
  push:
  pull_request:
  merge_group:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - run: pnpm build
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - run: pnpm puppeteer browsers install chrome
      - run: pnpm test
